---
- name: Comprobar si la contraseña de root es segura
  become: true
  ansible.builtin.shell: |
    test $(awk -F: '$1 == "root" && $2 ~ /^\$6\$/ {print $2}' /etc/shadow)
  register: algoritmo_password_root
  failed_when: false
  changed_when: algoritmo_password_root.rc != 0
  check_mode: false

- name: Configurar contraseña de root
  ansible.builtin.include_tasks: contrasena_de_root_configurar.yml
  when: algoritmo_password_root.changed
