- name: Configuración de /etc/sysctl.conf
  become: true
  ansible.builtin.template:
    src: sysctl.conf.j2
    dest: "/etc/sysctl.conf"
    backup: true
    mode: '0644'
  register: parametros_kernel_modificados
  notify:
    - 619_Reiniciar_host

- name: Mostrar configuración de los parámetros del kernel
  ansible.builtin.include_tasks: parametros_del_kernel_mostrar_configuracion.yml
  when: parametros_kernel_modificados.changed
